#!/bin/sh

JOKE=$(curl -s -H "Accept: text/plain" https://icanhazdadjoke.com/)

# Print the joke in the terminal
echo ""
echo "🤣 Here's a dad joke for you:"
echo "$JOKE"
echo ""


docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail

#trufflehog git file://$(pwd) --since-commit HEAD --results=verified,unknown --fail
